### ISSUE TITLE
missing includes from nav.html.twig?

### ISSUE THREAD

**Issue by AlastairBateman** [Flamenco/grav-plugin-core-service-manager#3]
nav.html.twig seems to refer to a few different partials

```
> cat nav.html.twig  | grep -n include
8:  {% include 'partials/logo.html.twig' %}
11: {% include 'partials/nav-user-details.html.twig' %}
13: {% include 'partials/nav-quick-tray.html.twig' %}
96: {% include 'partials/nav-pro.html.twig' ignore missing %}
```

I created blank versions of the first 3 files to get it working:

```
touch logo.html.twig
touch nav-user-details.html.twig
touch nav-quick-tray.html.twig
```

The partials folder the plugin is installed in (`/apps/www/grav/user/plugins/core-service-manager/admin/templates-grav/partials` - I'm using the Docker image) only has the `nav.html.twig` file and seems to be causing a 400 exception on the admin portal? 

I'm just playing around with Grav so don't consider myself an expert, but it's a relatively fresh install, based on the Docker Image (https://hub.docker.com/r/garywiz/docker-grav/). Grav has been updated to 1.4.3 via the GUI after the initial Docker container creation (which was 1.1.1 from memory).

**Comment by AlastairBateman** [comment]
I believe the core-service-manager was installed as a dependency of the [Admin Power Tools plugin](https://github.com/Flamenco/admin-power-tools) plugin.

**Comment by Flamenco** [comment]
All those partials are located in plugins/admin/themes/grav/templates/partials.  They should not live anywhere else, and should be resolved.  

**What version of admin is installed?**

Keep in mind that nav.html.twig should be exactly the same as the one in plugins/admin/themes/grav/templates/partials, but with a few hooks added.

@AlastairBateman, I think there might be another issue causing this.

<img width="1665" alt="screen shot 2018-05-01 at 10 44 29 pm" src="https://user-images.githubusercontent.com/819940/39502991-4a7f103a-4d91-11e8-94c5-7334b916cd6f.png">

**Comment by Flamenco** [comment]
Perhaps your distribution removed those files from the admin?

**Comment by AlastairBateman** [comment]
You might be right. The files seem to be in a freshly downloaded .zip from getgrav.org, but not in the docker image. The Docker image was updated a couple of years ago, but I would've thought updating Grav from within the admin page would've sorted that out. Maybe not. 

I'll do a bit more research. Thanks for your help. This one can probably be considered closed.
