### ISSUE TITLE
grav.CRITICAL: Constant OS_WINDOWS already defined

### ISSUE THREAD

**Issue by codiflow** [Flamenco/grav-plugin-core-service-manager#6]
After updating grav-plugin-core-service-manager I get the following error message when I try to load my website:

> grav.CRITICAL: Constant OS_WINDOWS already defined

After commenting out lines 37,38 and 41,42 in file `/user/plugins/core-service-manager/classes/Net/LDAP2/MYPEAR.php` which contains `define('OS_WINDOWS', true);` and `define('OS_UNIX',    false);` and vice versa everything works fine.

I think this is a bug. If you need more information just tell me.

**Comment by Flamenco** [comment]
Thanks for the bug report.

We renamed our embedded PEAR.php to MYPEAR.php because there were conflicts with other Grav plugins that did the same.  So most likely this is caused by another plugin, and not 
Grav core, getting loaded first. 

In this case, It would be best to check if defined first, instead of commenting out.  I will push a fix today.

**Comment by codiflow** [comment]
Unfortunately it doesn't work. I still get the following error message after the update:

> E_NOTICE - Constant OS_WINDOWS already defined

I don't know why but it only works with commenting out the following passage:

```
if (substr(PHP_OS, 0, 3) == 'WIN') {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        define('OS_WINDOWS', true);
        define('OS_UNIX', false);
    }
    define('MYPEAR_OS', 'Windows');
} else {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        #define('OS_WINDOWS', false);
        #define('OS_UNIX', true);
    }
    define('MYPEAR_OS', 'Unix'); // blatant assumption
}
```

**Comment by Flamenco** [comment]
1.  Did the error at least change from something else to `E_NOTICE`?
2. Is it the `other` plugin that is now reporting this error?

**Comment by codiflow** [comment]
1. Doesn't seem so. This is the GRAV log entry:

`grav.CRITICAL: Constant OS_WINDOWS already defined - Trace: #0 [internal function]: Whoops\Run->handleError(8, 'Constant OS_WIN...', '/usr/share/php/...', 41) #1 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Debugger.php(314): call_user_func(Array, 8, 'Constant OS_WIN...', '/usr/share/php/...', 41) #2 [internal function]: Grav\Common\Debugger->deprecatedErrorHandler(8, 'Constant OS_WIN...', '/usr/share/php/...', 41, Array) #3 /usr/share/php/PEAR.php(41): define('OS_WINDOWS', false) #4 /usr/share/php/Mail.php(48): require_once('/usr/share/php/...') #5 /var/www/html/MYSITE/htdocs/inc/email.php(3): require_once('/usr/share/php/...') #6 /var/www/html/MYSITE/htdocs/user/themes/pinpress/pinpress.php(6): require_once('/var/www/html/s...') #7 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Themes.php(188): include('/var/www/html/s...') #8 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Themes.php(61): Grav\Common\Themes->load() #9 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Themes.php(51): Grav\Common\Themes->initTheme() #10 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Processors/ThemesProcessor.php(18): Grav\Common\Themes->init() #11 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\ThemesProcessor->process() #12 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #13 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('themes', 'Themes', Object(Closure)) #14 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #15 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #16 /var/www/html/MYSITE/htdocs/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->measureTime('themes', 'Themes', Object(Closure)) #17 /var/www/html/MYSITE/htdocs/index.php(54): Grav\Common\Grav->process() #18 {main} [] []`

2. I don't really know. How can I find that out?

**Comment by Flamenco** [comment]
That exception is coming from `/usr/share/php/Mail.php` and that is including `/usr/share/php/PEAR.php`.  So that answers both my questions.

Our plugin is now defining those constants, and your theme is calling PEAR on your OS.  The theme is now throwing the exception.

Please try this: 

Instead of defining the constants, let's include PEAR from your OS.  That will define the constants for us.
So remove 

```
if (substr(PHP_OS, 0, 3) == 'WIN') {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        define('OS_WINDOWS', true);
        define('OS_UNIX', false);
    }
    define('MYPEAR_OS', 'Windows');
} else {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        #define('OS_WINDOWS', false);
        #define('OS_UNIX', true);
    }
    define('MYPEAR_OS', 'Unix'); // blatant assumption
}
```
and replace it with
```
include ('/usr/share/php/PEAR.php')
// or
include('pear.php')
```

That should make both files happy.

Please let me know if one or both work.   I am hoping the second one, without the path does...

**Comment by codiflow** [comment]
You meant like this?

`include('pear.php');
/*
if (substr(PHP_OS, 0, 3) == 'WIN') {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        define('OS_WINDOWS', true);
        define('OS_UNIX', false);
    }
    define('MYPEAR_OS', 'Windows');
} else {
    if (!defined('OS_WINDOWS') && !defined('OS_UNIX')) {
        #define('OS_WINDOWS', false);
        #define('OS_UNIX', true);
    }
    define('MYPEAR_OS', 'Unix'); // blatant assumption
}
*/`

Its working as far as I can see.

**Comment by codiflow** [comment]
But that's only a fix for me not for everyone isn't it?

**Comment by Flamenco** [comment]
Great.  I will update code to check if pear.php is available, and if so call that, if not call my code block, with the include guards.  That should fix it for everyone. 

Thanks for working with me!

**Comment by codiflow** [comment]
And I have to thank you for fixing this bug ;-)

Am 12. Dezember 2018 21:15:21 MEZ schrieb Flamenco <notifications@github.com>:
>Great.  I will update code to check if pear.php is available, and if so
>call that, if not call my code block, with the include guards.  That
>should fix it for everyone. 
>
>Thanks for working with me!


---------------------------------------------------------

Christian Süßenguth
Inhaber | cs@sweetgood.de

---------------------------------------------------------

Sweetgood - IT's better than good

Christian Süßenguth
Rother Str. 1
D-91174 Spalt

E-Mail: cs@sweetgood.de
Telefon: +49 (0) 9175 441 9 551
Fax: +49 (0) 3222 644 133 8
Web: https://www.sweetgood.de

---------------------------------------------------------

Think green. Keep it on the screen!

**Comment by Flamenco** [comment]
@codiflow I ended up just changed the constant names.
