### ISSUE TITLE
Conflict with the new parent-page explorer of Grav

### ISSUE THREAD

**Issue by Romarain** [Flamenco/grav-plugin-core-service-manager#7]
During a page creation, there's the possibility to chose in what parent page to insert the new page :

![2019-08-07_23h18m07s_chrome](https://user-images.githubusercontent.com/22033256/62662453-6a2a1b00-b974-11e9-9835-ae1f576db035.jpg)

But if the Core-service-manager plugin is activated, when clicking on the <root> button, the Javascript doesn't open the popup, wich should be this one : 

![2019-08-07_23h58m20s_chrome](https://user-images.githubusercontent.com/22033256/62662488-89c14380-b974-11e9-82ef-ae02ed06fa3a.jpg)

After investigating with Chrome's inspector, it appears that the console returns an error right after having clicked on the button :

![2019-08-07_23h59m18s_chrome](https://user-images.githubusercontent.com/22033256/62662497-934aab80-b974-11e9-9387-27c09e2878a0.jpg)

# Aditional information

An other plugin seems to conflict with the new Grav's ViewJS filetree explorer : the `widget` plugin. (see the related ticket : https://github.com/sojimaxi/grav-plugin-widget/issues/19)

I have disabled all plugins and tested one by one, and obtained two different errors with the Widget plugin (infinite reload) and the Core-service-manager (no loading of the popup at all).

**Comment by Flamenco** [comment]
@Romarain Thanks for the report.  We will look in this soon.

**Comment by Flamenco** [comment]
Our plugin adds a bunch of stubs inside the existing template, and it seems the Grav team did some major refactoring in this release.

There are **many** other issues in various other admin locations that were also fixed by this commit.

Fixed by https://github.com/Flamenco/grav-plugin-core-service-manager/commit/3bf612f72c8515d1c4e57c9047e495e7400fc63c

**Comment by Romarain** [comment]
@Flamenco I didn't understand your answer. Do you mean you fixed it in the commit ? So I have to update the admin plugin ?

**Comment by Flamenco** [comment]
@Romarain Yes.  this issue is fixed, along with about 15 or 20 other ones that have not been reported yet.

It might take a couple hours before Grav propagates the release to trigger an auto-update.

**Comment by Romarain** [comment]
@Flamenco : Sir, hat down ! Congratulation for that lightning speed fix, and a big thank you from a tiny dev.
