### ISSUE TITLE
v1.0.18 creates duplicate items in left sidebar in Grav 1.7 beta 7

### ISSUE THREAD

**Issue by SteveBaumann** [Flamenco/grav-plugin-core-service-manager#9]
Upon installation of CSM v1.0.18 in Grav 1.7 beta 7, duplicate items are created in the left sidebar of the Admin Console. This has been tested and replicated (see https://github.com/getgrav/grav/issues/2656). 
![duplicate-items_left-sidebar_after-core-service-manager](https://user-images.githubusercontent.com/11002590/64357148-f69e1c80-cfb8-11e9-8110-1d597a440702.png)

Upon removal of CSM from Plugins directory, items immediately disappear.

**Comment by Flamenco** [comment]
Should be an easy fix.  Thanks for reporting.

**Comment by Flamenco** [comment]
BTW, this is due to changes in `AdminPanel v1.10.0-beta.7`, not `Grav 1.7`.

**Comment by SteveBaumann** [comment]
That makes sense. Thanks.

**Comment by mahagr** [comment]
In the new version of Admin you can dynamically add all the menu items. If something is missing that you need, consider opening an issue. :)

**Comment by Flamenco** [comment]
Fixed in https://github.com/Flamenco/grav-plugin-core-service-manager/releases/tag/1.0.19

**Comment by Flamenco** [comment]
@mahagr I would like to merge much of this core-service-manager functionality into Grav core.  It is a PITA to keep aligned with the admin; very powerful but very simple.  I have been using it for more than a year with about 30 Grav plugins (about 5 of them are in Grav registry).  Have you had a chance to look at some of the source code?

**Comment by mahagr** [comment]
Please open an issue to Grav or Admin (whichever is the right place) for getting the functionality into Grav itself. The easiest way to get the functionality in would be to send few smaller pull requests adding the needed functionality.

**Comment by Flamenco** [comment]
@mahagr The issue with your PR suggestion is:

1. Both core and admin need to be updated.  The core will need the ServiceManager layer, and the Admin plugin will need the hooks added to the templates.
2. This will be a significant undertaking and we cannot spend the time crafting a PR without the blessing of Mr. Miller and Team Grav.
3.  If interested, we would ideally have a discussion about the API before proceeding.

FYI The goal of this plugin is to integrate adding and consuming resources to Grav (menu items, scripts, stylesheets, background services, etc) using a common syntax, without the need to understand application lifecycle, and to provide a global way for the runtime and other plugins to monitor and manage said resources.  When we started using Grav a couple of years ago, we found the plugin 'hook based approach' was tedious and error prone.  From our experience writing several operating systems for decades, we learned the 'whiteboard' approach for registering resources to always be the best design for extensibility and maintainability.

Obviously this is opinion based, and the complexity may not outweigh the benefits.  Please have a look at the [documentation](http://www.twelvetone.tv/docs/developer-tools/grav-plugins/grav-core-service-manager) and respond if you think this is something that would be embraced over there.

**Comment by mahagr** [comment]
I'll get back to you.
